from float_binary import *
A=integer_binary(int(input("Введите первое целое число")))
B=integer_binary(int(input("Введите второе целое число")))
print("Число A:")
A.show()
print("Число B:")
B.show()
print("Сумма:") 
(A+B).show()
print("Разность:")
(A-B).show()
print("Произведение:")
(A*B).show()
print("Деление:")
print(A/B)
A=float_binary(float(input("Введите первое дробное число")))
B=float_binary(float(input("Введите второе целое число")))
print("Число A:")
A.show()
print("Число B:")
B.show()
print("Сумма:") 
(A+B).show()